name: 'Terraform Pipeline using GitHub Actions Self-Hosted Runner'

on:
  push:
    branches: ["main", "feature"] 
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: [self-hosted, linux, x64]
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.6

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init