name: 'Terraform GitHub Actions hosted on self-hosted runners'

on:
  push:
    branches: ["main", "feature"] 
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip
          tar xzf terraform_0.14.3_linux_amd64.zip
      #     mv terraform /usr/local/bin/
      # - name: terraform fmt
      #   id: fmt
      #   run: terraform fmt
      #   continue-on-error: false